apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: emptydir-volume
          mountPath: /emptydir
    - name: nginx
      image: nginx
      volumeMounts:
        - name: emptydir-volume
          mountPath: /emptydir
  volumes:
    - name : emptydir-volume
      emptyDir: {}