apiVersion: v1
kind: Pod
metadata:
  name: pv-hostpath-pod
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: pv-hostpath-volume
          mountPath: /pv-hostpath
  volumes:
    - name : pv-hostpath-volume
      persistentVolumeClaim:
        claimName: pvc-hostpath