apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: app
  template:
    metadata:
      labels:
        app: nginx
        tier: app
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
