apiVersion: batch/v1
kind: CronJob
metadata:
  name: pi-cron-job
spec:
  schedule: "*/3 * * * *"
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      completions: 5
      parallelism: 2
      backoffLimit: 4
      activeDeadlineSeconds: 200
      ttlSecondsAfterFinished: 100
      template:
        metadata:
          labels:
            name: calc-pi
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 50
          containers:
            - name: pi
              image: perl:5.34.0
              command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
